import { createAction, createSlice } from "@reduxjs/toolkit";
import { IUser } from "../../type/backend";

export interface UserState {
  isPending: boolean;
  isError: boolean;
  data: IUser[];
  errors: any;

  isCreating: boolean;
  isCreateSuccess: boolean;

  isUpdating: boolean;
  isUpdateSuccess: boolean;

  isDeleting: boolean;
  isDeleteSuccess: boolean;
}

const initialState: UserState = {
  isPending: false,
  isError: false,
  isCreating: false,
  isCreateSuccess: false,

  isUpdating: false,
  isUpdateSuccess: false,

  isDeleting: false,
  isDeleteSuccess: false,

  data: [],
  errors: [],
};

export const loginPending = createAction<{ email: string; password: string }>(
  "loginPending"
);
export const logout = createAction("logout");

export const fetchUserPending = createAction("fetchUserPending");
export const fetchUserSuccess = createAction<IUser[]>("fetchUserSuccess");
export const fetchUserFailed = createAction("fetchUserFailed");

export const createUserPending = createAction<{ email: string; name: string }>(
  "createUserPending"
);
export const createUserSuccess = createAction("createUserSuccess");
export const createUserFailed = createAction("createUserFailed");

export const deleteUserPending = createAction<{ id: number }>(
  "deleteUserPending"
);
export const deleteUserSuccess = createAction("deleteUserSuccess");
export const deleteUserFailed = createAction("deleteUserFailed");

export const updateUserPending = createAction<{
  id: number;
  email: string;
  name: string;
}>("updateUserPending");
export const updateUserSuccess = createAction("updateUserSuccess");
export const updateUserFailed = createAction("updateUserFailed");

// Define the slice
export const userSlice = createSlice({
  name: "user",
  initialState,
  // The `reducers` field lets us define reducers and generate associated actions
  reducers: {},
  // Add more reducers here...
  // The `extraReducers` field lets the slice handle actions defined elsewhere,
  // including actions generated by createAsyncThunk or in other slices.
  extraReducers: (builder) => {
    builder
      .addCase(fetchUserPending, (state, action) => {
        state.isPending = true;
        state.isError = false;
      })
      .addCase(fetchUserSuccess, (state, action) => {
        state.isPending = false;
        state.isError = false;
        state.data = action.payload;
      })
      .addCase(fetchUserFailed, (state, action) => {
        state.isPending = false;
        state.isError = true;
        state.errors = action.payload;
      })
      .addCase(createUserPending, (state, action) => {
        state.isCreating = true;
        state.isError = false;
        state.isCreateSuccess = false;
      })
      .addCase(createUserSuccess, (state, action) => {
        state.isCreating = false;
        state.isCreateSuccess = true;
        state.isError = false;
      })
      .addCase(createUserFailed, (state, action) => {
        state.isCreating = false;
        state.isCreateSuccess = false;
        state.isError = true;
        state.errors = action.payload;
      })
      .addCase(updateUserPending, (state, action) => {
        state.isUpdating = true;
        state.isError = false;
        state.isUpdateSuccess = false;
      })
      .addCase(updateUserSuccess, (state, action) => {
        state.isUpdating = false;
        state.isUpdateSuccess = true;
        state.isError = false;
      })
      .addCase(updateUserFailed, (state, action) => {
        state.isUpdating = false;
        state.isUpdateSuccess = false;
        state.isError = true;
        state.errors = action.payload;
      })
      .addCase(deleteUserPending, (state, action) => {
        state.isDeleting = true;
        state.isError = false;
        state.isDeleteSuccess = false;
      })
      .addCase(deleteUserSuccess, (state, action) => {
        state.isDeleting = false;
        state.isDeleteSuccess = true;
        state.isError = false;
      })
      .addCase(deleteUserFailed, (state, action) => {
        state.isDeleting = false;
        state.isDeleteSuccess = false;
        state.isError = true;
        state.errors = action.payload;
      });
  },
});

export const {} = userSlice.actions;

export default userSlice.reducer;
